version: '3.2'

services:
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ../config/.env
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 100
    ports:
      - "3306:3306"
    networks:
      - external-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - external-network

networks:
  external-network:
    external: true
