version: "3.2"

name: "ctf-platform-telegram"

services:
  app:
    build: ..
    command: python3 main.py
    env_file:
      - ./config/.env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - internal-network

  mysql:
    image: mysql
    env_file:
      - ./config/.env
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 100
    ports:
      - "3306:3306"
    networks:
      - internal-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - internal-network

networks:
  internal-network:
  external-network:
    external: true
